class AddMissingIndexes < ActiveRecord::Migration[7.0]
  def change
    add_index :assess_campaigns, :status
    add_index :certifications, :issued_at
    add_index :certifications, :expires_at
    add_index :companies, :target_segment
    add_index :companies, :location
    add_index :contents, :format
    add_index :contents, :level
    add_index :contents, :tags
    add_index :contents, :lp_url
    add_index :discussions, :status
    add_index :discussions, :subject
    add_index :leads, :conversion_state
    add_index :leads, :email
    add_index :leads, :lead_source
    add_index :leads, :funnel_stage
    add_index :marketing_campaigns, :channel
    add_index :marketing_campaigns, :scheduled_at
    add_index :noticed_events, :type
    add_index :noticed_events, :notifications_count
    add_index :noticed_notifications, :type
    add_index :noticed_notifications, :read_at
    add_index :noticed_notifications, :seen_at
    add_index :posts, :views
    add_index :posts, :published_at
    add_index :pricing_rules, :name
    add_index :pricing_rules, :discount_pct
    add_index :pricings, :currency
    add_index :pricings, :charge_type
    add_index :pricings, :frequency
    add_index :pricings, :state
    add_index :products, :status
    add_index :products, :kind
    add_index :products, :source
    add_index :products, :country
    add_index :quotes, :status
    add_index :quotes, :email
    add_index :quotes, :phone
    add_index :replies, :status
    add_index :reviews, :rating
    add_index :reviews, :status
    add_index :saa_s_leads, :status
    add_index :saa_s_plans, :tier
    add_index :saa_s_plans, :active
    add_index :saa_s_products, :status
    add_index :saa_s_products, :active
    add_index :users, :role
    add_index :users, :name
  end
end
